// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package main

import "fmt"

const _TokenTypeName = "UnknownArgumentNameIdentifierStringLiteralHexLiteralDecimalLiteralPathLiteralLeftParensRightParensEOF"

var _TokenTypeIndex = [...]uint8{0, 7, 19, 29, 42, 52, 66, 77, 87, 98, 101}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenTypeIndex)-1) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenTypeName[_TokenTypeIndex[i]:_TokenTypeIndex[i+1]]
}
